name: gitartwork from a contribution graph
on: 
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          # Use this username's contribution graph  
          user_name: priyanshubuddy
          # Text on contribution graph 
          text: PRIYANSHU
      - name: Modify SVG height
        run: |
          sed -i 's/height="[0-9]\+/height="130/' output.svg
      - uses: jasineri/simple-push-action@v1
