name: Generate gitartwork SVG from contribution graph
on:
  push:
  schedule:
    - cron: '* */24 * * *'

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate gitartwork
        uses: jasineri/gitartwork@v1
        with:
          user_name: priyanshubuddy
          text: PRIYANSHU DUBEY

#      - name: Push generated artwork
#        uses: jasineri/simple-push-action@v1
